/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function captureScreenshot(): Promise<Buffer>;
export declare function captureScreenshotByScreenId(screenId: number): Buffer;
export interface ScreenInfo {
  id: number;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  scaleFactor: number;
  frequency: number;
  isPrimary: boolean;
}
export declare function listScreens(): Array<ScreenInfo>;
