/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function captureScreenshot(): Promise<Buffer>

export declare function captureScreenshotByScreenId(screenId: number): Promise<Buffer>

export declare function listScreens(): Array<ScreenInfo>

export interface ScreenInfo {
  id: number
  x: number
  y: number
  width: number
  height: number
  rotation: number
  scaleFactor: number
  frequency: number
  isPrimary: boolean
}
